#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# airflow/setup.sh
# One-time Airflow initialisation. Run from the project root:
#   bash airflow/setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

PROJECT="$(cd "$(dirname "$0")/.." && pwd)"

export AIRFLOW_HOME="$PROJECT/airflow"
export PYTHONPATH="$PROJECT/src"
export AIRFLOW__CORE__LOAD_EXAMPLES=False
export AIRFLOW__CORE__DAGS_FOLDER="$AIRFLOW_HOME/dags"

PYTHON="$PROJECT/.venv/bin/python"
PIP="$PROJECT/.venv/bin/pip"
AIRFLOW="$PROJECT/.venv/bin/airflow"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Sounders Analytics Engine — Airflow Setup             ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Install Airflow into the existing venv ────────────────────────────────────
echo "[1/3] Installing apache-airflow into .venv…"
"$PIP" install -q "apache-airflow>=3.0.0"
echo "      Done."

# ── Initialise the Airflow metadata database ──────────────────────────────────
echo "[2/3] Initialising Airflow database…"
"$AIRFLOW" db migrate
echo "      Done."

echo ""
echo "Setup complete."
echo ""
echo "Next steps:"
echo "  1. Fill in SMTP credentials in .env"
echo "  2. Start Airflow:  bash airflow/start.sh"
echo "  3. Open:           http://localhost:8080"

PASSWD_FILE="$AIRFLOW_HOME/simple_auth_manager_passwords.json.generated"
if [ -f "$PASSWD_FILE" ]; then
    echo ""
    echo "Login credentials (auto-generated by Airflow 3):"
    echo "  Username: admin"
    echo "  Password: $(python3 -c "import json; d=json.load(open('$PASSWD_FILE')); print(d.get('admin','see $PASSWD_FILE'))")"
fi
echo ""
